uploads = []
outputs = []

[[generated]]
id = "ZJE_5wDdrZ3BPY1IUwUdp"
uri = "file://artifacts/pitch-video/public/images/human_connected.png"
type = "image"
title = "connected remote worker"

[[generated]]
id = "F-TlPFYXzGpSbkTqmVdV9"
uri = "file://artifacts/pitch-video/public/images/human_team.png"
type = "image"
title = "celebrating team"

[[generated]]
id = "EtzM907oq54GwMhqEpy4h"
uri = "file://artifacts/pitch-video/public/images/human_isolated.png"
type = "image"
title = "isolated overwhelmed person"
